name: Auto Update Package

on:
  schedule:
    - cron: '0 2 * * *' # Проверка каждый день в 02:00 ночи по UTC
  workflow_dispatch:     # Позволяет запустить обновление вручную кнопкой на GitHub

permissions:
  contents: write # Даем право боту делать коммиты в наш репозиторий

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repo
        uses: actions/checkout@v7.0.0

      - name: Install Nix
        uses: cachix/install-nix-action@v31.11.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check Upstream Release and Update
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # === НАСТРОЙКА ===
          UPSTREAM_REPO="ElyPrismLauncher/Launcher"
          # =================

          echo "Проверяем последний релиз в $UPSTREAM_REPO..."
          
          LATEST_VERSION=$(gh release view --repo $UPSTREAM_REPO --json tagName --template '{{.tagName}}')
          
          CURRENT_VERSION=$(grep -oP 'version = "\K[^"]+' package.nix)

          if [ "$LATEST_VERSION" = "$CURRENT_VERSION" ]; then
            echo "Обновлений нет. Текущая версия $CURRENT_VERSION актуальна."
            exit 0
          fi

          echo "Найдена новая версия: $LATEST_VERSION (у нас: $CURRENT_VERSION)"

          NEW_URL_X86="https://github.com/$UPSTREAM_REPO/releases/download/$LATEST_VERSION/PineconeMC-Linux-x86_64.AppImage"
          NEW_URL_ARM="https://github.com/$UPSTREAM_REPO/releases/download/$LATEST_VERSION/PineconeMC-Linux-aarch64.AppImage"

          echo "Скачиваем файлы и вычисляем новые SHA256-хеши через Nix..."
          
          STORE_PATH_X86=$(nix-prefetch-url "$NEW_URL_X86" --type sha256)
          NEW_HASH_X86=$(nix hash to-sri --type sha256 "$STORE_PATH_X86")

          STORE_PATH_ARM=$(nix-prefetch-url "$NEW_URL_ARM" --type sha256)
          NEW_HASH_ARM=$(nix hash to-sri --type sha256 "$STORE_PATH_ARM")

          echo "Обновляем package.nix..."
          sed -i "s|version = \".*\"; # UPDATE_VERSION|version = \"$LATEST_VERSION\"; # UPDATE_VERSION|" package.nix
          sed -i "s|url = \".*\"; # UPDATE_URL_X86|url = \"$NEW_URL_X86\"; # UPDATE_URL_X86|" package.nix
          sed -i "s|hash = \".*\"; # UPDATE_HASH_X86|hash = \"$NEW_HASH_X86\"; # UPDATE_HASH_X86|" package.nix
          sed -i "s|url = \".*\"; # UPDATE_URL_ARM|url = \"$NEW_URL_ARM\"; # UPDATE_URL_ARM|" package.nix
          sed -i "s|hash = \".*\"; # UPDATE_HASH_ARM|hash = \"$NEW_HASH_ARM\"; # UPDATE_HASH_ARM|" package.nix

          echo "Коммитим изменения в репозиторий..."
          git config user.name "github-actions[bot]"
          git config user.email "41851857+github-actions[bot]@users.noreply.github.com"
          git add package.nix
          git commit -m "chore: автоматическое обновление до версии $LATEST_VERSION"
          git push
